import sqlite3

# DB 파일명
DB_NAME = 'english_study.db'

def init_db():
    """DB를 초기화하고 데이터를 채워넣는 함수"""
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()

    # 기존 데이터 삭제 (업데이트 반영)
    cursor.execute("DROP TABLE IF EXISTS study_data")

    # 테이블 생성
    cursor.execute('''
    CREATE TABLE study_data (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        level TEXT,
        topic TEXT,
        sentences TEXT
    )
    ''')

    # --- 30개 주제 전체 데이터 ---
    study_list = [
        # ==========================================
        # 1. 초급 (Beginner)
        # ==========================================
        ("초급 (Beginner)", "01. 인사하기", """👩: Hello, how are you today?\n(안녕하세요, 오늘 기분 어때요?)\n\n👨: I am fine, thank you. And you?\n(전 좋아요, 고마워요. 당신은요?)\n\n👩: I am doing great. Nice to meet you.\n(저도 아주 좋아요. 만나서 반가워요.)\n\n👨: Nice to meet you too.\n(저도 만나서 반가워요.)\n\n👩: What brings you here today?\n(오늘은 무슨 일로 오셨나요?)\n\n👨: I just came to study English.\n(그냥 영어 공부하러 왔어요.)\n\n👩: That sounds wonderful. Let's study together.\n(멋지네요. 같이 공부해요.)\n\n👨: Sure! I will do my best.\n(물론이죠! 최선을 다할게요.)\n\n👩: Do you live near here?\n(이 근처에 사시나요?)\n\n👨: Yes, I live just 5 minutes away.\n(네, 5분 거리에 살아요.)"""),
        ("초급 (Beginner)", "02. 자기소개", """👩: Can you introduce yourself?\n(자기소개 좀 해주실래요?)\n\n👨: My name is Min-su. I am from Korea.\n(제 이름은 민수예요. 한국에서 왔어요.)\n\n👩: What do you do for a living?\n(직업이 어떻게 되시나요?)\n\n👨: I work at an IT company.\n(저는 IT 회사에서 일해요.)\n\n👩: That sounds interesting. Do you like your job?\n(재미있겠네요. 일이 마음에 드세요?)\n\n👨: Yes, but it is very busy.\n(네, 하지만 매우 바빠요.)\n\n👩: How old are you, if I may ask?\n(실례지만 나이가 어떻게 되세요?)\n\n👨: I am 35 years old.\n(저는 35살입니다.)\n\n👩: Where do you live now?\n(지금은 어디 사세요?)\n\n👨: I live in Seoul with my wife.\n(아내와 함께 서울에 살아요.)"""),
        ("초급 (Beginner)", "03. 음식 주문", """👩: Welcome. What would you like to order?\n(어서오세요. 무엇을 주문하시겠어요?)\n\n👨: I would like a cheeseburger and coke.\n(치즈버거 하나랑 콜라 주세요.)\n\n👩: Is that for here or to go?\n(여기서 드시나요, 아니면 가져가시나요?)\n\n👨: For here, please.\n(여기서 먹고 갈게요.)\n\n👩: Would you like any side dishes?\n(사이드 메뉴는 필요 없으신가요?)\n\n👨: Can I get some french fries?\n(감자튀김 하나 주시겠어요?)\n\n👩: Sure. Anything else?\n(물론이죠. 다른 건요?)\n\n👨: That's all. How much is it?\n(그게 다예요. 얼마인가요?)\n\n👩: It's 10 dollars.\n(10달러입니다.)\n\n👨: Here is my credit card.\n(여기 제 신용카드요.)"""),
        ("초급 (Beginner)", "04. 길 묻기", """👩: Excuse me. Where is the subway station?\n(실례합니다. 지하철역이 어디인가요?)\n\n👨: Go straight and turn right at the corner.\n(쭉 가다가 모퉁이에서 오른쪽으로 도세요.)\n\n👩: Is it far from here?\n(여기서 먼가요?)\n\n👨: No, it takes only 5 minutes on foot.\n(아니요, 걸어서 5분밖에 안 걸려요.)\n\n👩: Can I take a bus there?\n(거기까지 버스를 탈 수 있나요?)\n\n👨: Yes, bus number 10 goes there.\n(네, 10번 버스가 거기로 가요.)\n\n👩: Where is the bus stop?\n(버스 정류장은 어디인가요?)\n\n👨: It is right in front of the bank.\n(은행 바로 앞에 있어요.)\n\n👩: Thank you very much for your help.\n(도와주셔서 정말 감사합니다.)\n\n👨: You're welcome. Have a nice day!\n(천만에요. 좋은 하루 보내세요!)"""),
        ("초급 (Beginner)", "05. 날씨 이야기", """👩: The weather is so nice today.\n(오늘 날씨가 정말 좋네요.)\n\n👨: Yes, it is very sunny and warm.\n(네, 아주 맑고 따뜻해요.)\n\n👩: Do you like summer or winter?\n(여름을 좋아하세요, 겨울을 좋아하세요?)\n\n👨: I like winter because I love snow.\n(저는 눈을 좋아해서 겨울을 좋아해요.)\n\n👩: I heard it will rain tomorrow.\n(내일은 비가 온다고 들었어요.)\n\n👨: Really? I should bring an umbrella.\n(정말요? 우산을 챙겨야겠네요.)\n\n👩: Is it cold outside now?\n(지금 밖이 추운가요?)\n\n👨: Yes, you should wear a coat.\n(네, 코트를 입는 게 좋아요.)\n\n👩: Thanks for letting me know.\n(알려줘서 고마워요.)\n\n👨: No problem. Stay warm!\n(별말씀을요. 따뜻하게 입으세요!)"""),
        ("초급 (Beginner)", "06. 취미 생활", """👩: What is your hobby?\n(취미가 뭐예요?)\n\n👨: I like watching movies on weekends.\n(저는 주말에 영화 보는 걸 좋아해요.)\n\n👩: What kind of movies do you like?\n(어떤 영화 장르를 좋아하세요?)\n\n👨: I love action movies. They are exciting.\n(액션 영화를 정말 좋아해요. 신나거든요.)\n\n👩: Do you play any sports?\n(운동하는 거 있나요?)\n\n👨: I play tennis sometimes.\n(가끔 테니스를 쳐요.)\n\n👩: Are you good at tennis?\n(테니스 잘 치세요?)\n\n👨: Not really. I am just a beginner.\n(아니요. 그냥 초보자예요.)\n\n👩: Let's play together next time.\n(다음에 같이 쳐요.)\n\n👨: That sounds like a good idea.\n(좋은 생각이에요.)"""),
        ("초급 (Beginner)", "07. 쇼핑하기", """👩: Can I help you find something?\n(무엇을 도와드릴까요?)\n\n👨: I am looking for a gift for my wife.\n(아내에게 줄 선물을 찾고 있어요.)\n\n👩: How about this scarf? It is popular.\n(이 스카프는 어떠세요? 인기가 많아요.)\n\n👨: It looks nice. How much is it?\n(좋아 보이네요. 얼마인가요?)\n\n👩: It is 50 dollars.\n(50달러입니다.)\n\n👨: That is a bit expensive. Do you have a discount?\n(좀 비싸네요. 할인되나요?)\n\n👩: Yes, it is 10% off today.\n(네, 오늘은 10% 할인해 드려요.)\n\n👨: Okay, I will take it.\n(알겠습니다, 이걸로 할게요.)\n\n👩: Do you need gift wrapping?\n(선물 포장해 드릴까요?)\n\n👨: Yes, please. Thank you.\n(네, 부탁해요. 감사합니다.)"""),
        ("초급 (Beginner)", "08. 시간 약속", """👩: What time is it now?\n(지금 몇 시예요?)\n\n👨: It is 2 o'clock.\n(2시입니다.)\n\n👩: We have a meeting at 3 o'clock, right?\n(우리 3시에 회의 있죠, 맞죠?)\n\n👨: Yes, we have one hour left.\n(네, 1시간 남았어요.)\n\n👩: Are you ready for the meeting?\n(회의 준비는 다 됐나요?)\n\n👨: almost. I need to print some papers.\n(거의요. 서류 몇 장만 출력하면 돼요.)\n\n👩: Let's go to the cafe before the meeting.\n(회의 전에 카페에 가요.)\n\n👨: Good idea. I need some coffee.\n(좋은 생각이에요. 커피가 좀 필요해요.)\n\n👩: Shall we meet at the lobby?\n(로비에서 만날까요?)\n\n👨: Okay, see you in 10 minutes.\n(네, 10분 뒤에 봐요.)"""),
        ("초급 (Beginner)", "09. 가족 소개", """👩: Do you have a big family?\n(가족이 많으신가요?)\n\n👨: No, I have a small family.\n(아니요, 가족이 적어요.)\n\n👩: How many people are in your family?\n(가족이 몇 명이에요?)\n\n👨: There are three people: me, my wife, and my son.\n(저, 아내, 아들 이렇게 셋이에요.)\n\n👩: How old is your son?\n(아들은 몇 살인가요?)\n\n👨: He is 5 years old. He is very cute.\n(5살이에요. 아주 귀엽죠.)\n\n👩: Do you have any brothers or sisters?\n(형제나 자매가 있나요?)\n\n👨: I have one older sister.\n(누나가 한 명 있어요.)\n\n👩: Does she live with you?\n(누나랑 같이 사나요?)\n\n👨: No, she lives in Busan.\n(아니요, 누나는 부산에 살아요.)"""),
        ("초급 (Beginner)", "10. 건강/기분", """👩: You look tired today. Are you okay?\n(오늘 피곤해 보여요. 괜찮아요?)\n\n👨: I have a headache. I didn't sleep well.\n(머리가 아파요. 잠을 잘 못 잤거든요.)\n\n👩: You should take some medicine.\n(약을 좀 드시는 게 좋겠어요.)\n\n👨: I already took some aspirin.\n(이미 아스피린을 좀 먹었어요.)\n\n👩: Did you go to see a doctor?\n(병원에는 가보셨나요?)\n\n👨: No, I think I just need some rest.\n(아니요, 그냥 휴식이 좀 필요한 것 같아요.)\n\n👩: Go home early and get some sleep.\n(일찍 집에 가서 좀 주무세요.)\n\n👨: I want to, but I have a lot of work.\n(그러고 싶은데 일이 너무 많아요.)\n\n👩: Health is the most important thing.\n(건강이 가장 중요해요.)\n\n👨: You are right. Thanks for caring.\n(맞아요. 걱정해 줘서 고마워요.)"""),

        # ==========================================
        # 2. 중급 (Intermediate)
        # ==========================================
        ("중급 (Intermediate)", "01. 주말 계획", """👩: Do you have any plans for this weekend?\n(이번 주말에 무슨 계획 있어?)\n\n👨: I'm thinking of going hiking with my friends.\n(친구들이랑 등산 갈까 생각 중이야.)\n\n👩: That sounds fun! Which mountain are you going to?\n(재밌겠다! 어느 산으로 가는데?)\n\n👨: We are going to Bukhansan. Want to join?\n(북한산으로 갈 거야. 같이 갈래?)\n\n👩: I'd love to, but I have a family dinner.\n(그러고 싶은데, 가족 저녁 식사가 있어.)\n\n👨: Oh, that's too bad. Maybe next time.\n(아, 아쉽네. 다음에 같이 가자.)\n\n👩: By the way, is the trail difficult?\n(그나저나, 등산 코스는 힘들어?)\n\n👨: It's a bit steep, but the view is amazing.\n(좀 가파르긴 한데, 경치가 끝내줘.)\n\n👩: Make sure to take lots of pictures.\n(사진 많이 찍어와.)\n\n👨: I definitely will. I'll show you later.\n(당연하지. 나중에 보여줄게.)"""),
        ("중급 (Intermediate)", "02. 여행 경험", """👩: Have you ever been to Jeju Island?\n(제주도 가본 적 있어?)\n\n👨: Yes, I went there last summer with my family.\n(응, 작년 여름에 가족들이랑 갔었어.)\n\n👩: How was it? Did you like the food?\n(어땠어? 음식은 맛있었어?)\n\n👨: Everything was perfect, especially the seafood.\n(모든 게 완벽했어, 특히 해산물이 최고였지.)\n\n👩: Did you visit Hallasan mountain?\n(한라산에도 가봤어?)\n\n👨: No, it was raining so we couldn't go.\n(아니, 비가 와서 못 갔어.)\n\n👩: That's a pity. You should try next time.\n(아쉽다. 다음에 꼭 가봐.)\n\n👨: Instead, we went to many beautiful cafes.\n(대신에 예쁜 카페를 많이 갔어.)\n\n👩: I plan to go there next month. Any recommendations?\n(나 다음 달에 갈 건데 추천해 줄 만한 곳 있어?)\n\n👨: You must try the black pork BBQ. It's delicious.\n(흑돼지 바베큐는 꼭 먹어봐. 진짜 맛있어.)"""),
        ("중급 (Intermediate)", "03. 영화/드라마", """👩: Have you seen 'Squid Game' on Netflix?\n(넷플릭스에서 '오징어 게임' 봤어?)\n\n👨: Yes, I watched the whole series in one day.\n(응, 하루 만에 전편을 다 봤어.)\n\n👩: It was so intense, wasn't it?\n(정말 강렬했지, 그치?)\n\n👨: I couldn't stop watching it. It was addictive.\n(멈출 수가 없었어. 중독성 있더라.)\n\n👩: Who was your favorite character?\n(가장 좋아하는 캐릭터가 누구였어?)\n\n👨: I liked the old man the most. He was mysterious.\n(난 할아버지가 제일 좋았어. 미스터리했잖아.)\n\n👩: I prefer romantic comedies over thrillers.\n(난 스릴러보다는 로맨틱 코미디를 더 좋아해.)\n\n👨: Really? Can you recommend a good one?\n(그래? 좋은 거 하나 추천해 줄래?)\n\n👩: 'About Time' is my all-time favorite movie.\n('어바웃 타임'이 내가 제일 좋아하는 영화야.)\n\n👨: I'll add it to my watch list. Thanks.\n(내 시청 목록에 추가해야겠다. 고마워.)"""),
        ("중급 (Intermediate)", "04. 요리/음식", """👩: Do you cook often at home?\n(집에서 요리 자주 해?)\n\n👨: I try to cook dinner at least three times a week.\n(일주일에 적어도 세 번은 저녁을 해 먹으려고 노력해.)\n\n👩: What is your signature dish?\n(가장 자신 있는 요리가 뭐야?)\n\n👨: I am pretty good at making Kimchi stew.\n(나 김치찌개는 꽤 잘 만들어.)\n\n👩: Sounds delicious. What's your secret ingredient?\n(맛있겠다. 너만의 비법 재료가 있어?)\n\n👨: I use pork belly and extra garlic.\n(삼겹살이랑 마늘을 많이 넣어.)\n\n👩: I usually just order delivery food.\n(난 보통 그냥 배달 시켜 먹어.)\n\n👨: Delivery is convenient but it can be unhealthy.\n(배달이 편하긴 한데 건강에 안 좋을 수도 있어.)\n\n👩: I know. I want to learn how to cook pasta.\n(알아. 나 파스타 만드는 법 배우고 싶어.)\n\n👨: Pasta is easy. I can teach you someday.\n(파스타는 쉬워. 내가 나중에 가르쳐 줄게.)"""),
        ("중급 (Intermediate)", "05. 직장 생활", """👩: How is your new job going?\n(새로운 직장은 어때?)\n\n👨: It's challenging but I'm learning a lot.\n(힘들긴 한데 배우는 게 많아.)\n\n👩: Are your colleagues nice to you?\n(동료들은 잘해줘?)\n\n👨: Most of them are friendly and helpful.\n(대부분 친절하고 잘 도와줘.)\n\n👩: Do you have to work overtime often?\n(야근 자주 해야 해?)\n\n👨: Sometimes, especially when there is a deadline.\n(가끔, 특히 마감일이 있을 때는.)\n\n👩: Don't work too hard. Health comes first.\n(너무 무리하지 마. 건강이 제일이야.)\n\n👨: Thanks. I try to leave the office on time.\n(고마워. 정시 퇴근하려고 노력 중이야.)\n\n👩: Let's grab a beer after work this Friday.\n(이번 주 금요일 퇴근하고 맥주 한잔하자.)\n\n👨: Sounds great. I really need a drink.\n(좋지. 진짜 술 한잔 필요했어.)"""),
        ("중급 (Intermediate)", "06. 대중교통", """👩: How do you usually commute to work?\n(보통 회사에 어떻게 출근해?)\n\n👨: I take the subway. It takes about 40 minutes.\n(지하철 타. 40분 정도 걸려.)\n\n👩: Isn't it crowded during rush hour?\n(출퇴근 시간에 붐비지 않아?)\n\n👨: It is packed. I can barely stand sometimes.\n(꽉 차. 가끔은 서 있기도 힘들어.)\n\n👩: Why don't you drive your car?\n(왜 차 운전해서 안 다녀?)\n\n👨: Traffic is terrible in the morning.\n(아침에 교통 체증이 끔찍하잖아.)\n\n👩: That makes sense. Parking is also an issue.\n(말 되네. 주차도 문제지.)\n\n👨: Exactly. The subway is faster and cheaper.\n(맞아. 지하철이 더 빠르고 싸.)\n\n👩: I usually take the bus, but it's often late.\n(난 보통 버스 타는데, 자주 늦게 와.)\n\n👨: Public transport in Seoul is good, but crowded.\n(서울 대중교통은 좋은데, 사람이 너무 많아.)"""),
        ("중급 (Intermediate)", "07. 영어 공부", """👩: Why are you learning English these days?\n(요즘 왜 영어 공부를 해?)\n\n👨: I want to travel abroad without a tour guide.\n(가이드 없이 해외여행을 가고 싶어서.)\n\n👩: That's a great motivation. How do you study?\n(동기부여가 확실하네. 어떻게 공부해?)\n\n👨: I use a mobile app and watch American dramas.\n(핸드폰 앱도 쓰고 미드도 봐.)\n\n👩: Is it helpful to watch dramas?\n(드라마 보는 게 도움이 돼?)\n\n👨: Yes, I can learn natural expressions and slang.\n(응, 자연스러운 표현이랑 속어를 배울 수 있어.)\n\n👩: Speaking is the hardest part for me.\n(난 말하기가 제일 어렵더라.)\n\n👨: Me too. I get nervous when I speak English.\n(나도 그래. 영어로 말할 때 긴장돼.)\n\n👩: We should practice speaking together.\n(우리 같이 말하기 연습하자.)\n\n👨: Good idea. Practice makes perfect.\n(좋은 생각이야. 연습만이 살길이지.)"""),
        ("중급 (Intermediate)", "08. 건강 습관", """👩: Do you work out regularly?\n(규칙적으로 운동해?)\n\n👨: I try to go to the gym three times a week.\n(일주일에 세 번은 헬스장 가려고 해.)\n\n👩: I want to lose some weight. Any tips?\n(나 살 좀 빼고 싶은데. 팁 있어?)\n\n👨: Drinking lots of water helps a lot.\n(물 많이 마시는 게 도움이 많이 돼.)\n\n👩: What about diet? Should I skip dinner?\n(식단은? 저녁을 굶어야 할까?)\n\n👨: No, just reduce carbohydrates and eat more veggies.\n(아니, 탄수화물 줄이고 채소 더 많이 먹어.)\n\n👩: I love bread and noodles too much.\n(난 빵이랑 면을 너무 좋아해서 문제야.)\n\n👨: Cutting down sugar is also very important.\n(설탕 줄이는 것도 진짜 중요해.)\n\n👩: It's so hard to stay healthy.\n(건강 유지하는 거 진짜 힘들다.)\n\n👨: But it's worth it. You feel much better.\n(그래도 가치 있어. 몸 상태가 훨씬 좋아지거든.)"""),
        ("중급 (Intermediate)", "09. 음악 감상", """👩: What kind of music do you listen to?\n(어떤 음악 듣는 거 좋아해?)\n\n👨: I mostly listen to K-pop and Jazz.\n(난 주로 케이팝이랑 재즈 들어.)\n\n👩: Do you have a favorite singer?\n(좋아하는 가수 있어?)\n\n👨: I am a big fan of BTS. Their energy is amazing.\n(나 BTS 엄청 팬이야. 에너지가 대단해.)\n\n👩: I like Jazz too. It helps me relax.\n(나도 재즈 좋아해. 편안하게 해 주잖아.)\n\n👨: Do you play any musical instruments?\n(다룰 줄 아는 악기 있어?)\n\n👨: I can play the guitar a little bit.\n(기타 조금 칠 줄 알아.)\n\n👩: Wow, can you play a song for me later?\n(와, 나중에 곡 하나 연주해 줄 수 있어?)\n\n👨: Sure, if I practice enough.\n(물론이지, 연습 충분히 하면.)\n\n👩: Music makes life much more colorful.\n(음악은 삶을 훨씬 다채롭게 만들어 줘.)"""),
        ("중급 (Intermediate)", "10. 패션/쇼핑", """👩: I like your jacket. Where did you get it?\n(재킷 예쁘다. 어디서 샀어?)\n\n👨: I bought it online last week. It was on sale.\n(지난주에 인터넷으로 샀어. 세일 중이었거든.)\n\n👩: You have a good sense of style.\n(너 패션 감각이 좋구나.)\n\n👨: Thanks. I usually wear casual clothes.\n(고마워. 난 보통 캐주얼하게 입어.)\n\n👩: I need to buy a dress for a wedding.\n(나 결혼식 때 입을 원피스 사야 하는데.)\n\n👨: Let's go to the department store this weekend.\n(이번 주말에 백화점 가자.)\n\n👩: Do you think red suits me?\n(빨간색이 나한테 어울릴까?)\n\n👨: I think navy or black would look better on you.\n(내 생각엔 네이비나 검정이 더 잘 어울릴 것 같아.)\n\n👩: Okay, I will trust your advice.\n(알았어, 네 조언 믿을게.)\n\n👨: Shopping is always fun.\n(쇼핑은 언제나 재밌지.)"""),

        # ==========================================
        # 3. 고급 (Advanced)
        # ==========================================
        ("고급 (Advanced)", "01. AI의 미래", """👩: What do you think about the future of AI?\n(AI의 미래에 대해 어떻게 생각하세요?)\n\n👨: I believe AI will significantly improve our productivity.\n(저는 AI가 우리의 생산성을 크게 향상시킬 것이라고 믿습니다.)\n\n👩: But aren't you worried about job losses?\n(하지만 일자리 감소에 대해서는 걱정되지 않나요?)\n\n👨: New jobs will be created as technology advances.\n(기술이 발전함에 따라 새로운 직업들이 생겨날 겁니다.)\n\n👩: That's true, but adapting might be hard for some.\n(맞아요, 하지만 적응하는 게 어떤 이들에겐 어려울 수 있죠.)\n\n👨: Education systems need to change to prepare people.\n(사람들을 대비시키기 위해 교육 시스템이 변해야 합니다.)\n\n👩: Do you think AI can ever have real emotions?\n(AI가 진짜 감정을 가질 수 있을 거라고 보세요?)\n\n👨: That is a complex philosophical question.\n(그건 복잡한 철학적 질문이네요.)\n\n👩: I think empathy is unique to humans.\n(저는 공감 능력은 인간만의 고유한 것이라 생각해요.)\n\n👨: Maybe, but AI can simulate empathy very well.\n(그럴지도요, 하지만 AI는 공감을 매우 잘 흉내 낼 수 있죠.)"""),
        ("고급 (Advanced)", "02. 환경 문제", """👩: Global warming is becoming a serious issue.\n(지구 온난화가 심각한 문제가 되고 있습니다.)\n\n👨: I agree. We need to reduce carbon emissions immediately.\n(동의합니다. 우리는 즉시 탄소 배출을 줄여야 해요.)\n\n👩: What can individuals do to help?\n(개인이 도울 수 있는 일은 무엇이 있을까요?)\n\n👨: Starting with recycling is a small but important step.\n(재활용부터 시작하는 것이 작지만 중요한 첫걸음입니다.)\n\n👩: I stopped using plastic straws recently.\n(저는 최근에 플라스틱 빨대 사용을 중단했어요.)\n\n👨: That is great. Plastic pollution is harming the ocean.\n(훌륭하네요. 플라스틱 오염이 바다를 해치고 있죠.)\n\n👩: Governments should enforce stricter regulations.\n(정부가 더 강력한 규제를 시행해야 합니다.)\n\n👨: Companies also need to invest in green energy.\n(기업들도 친환경 에너지에 투자해야 해요.)\n\n👩: It is our responsibility to protect the planet.\n(지구를 보호하는 것은 우리의 책임입니다.)\n\n👨: Absolutely. For the next generation.\n(맞습니다. 다음 세대를 위해서요.)"""),
        ("고급 (Advanced)", "03. 재택 근무", """👩: Do you prefer working from home or at the office?\n(재택근무와 사무실 근무 중 무엇을 선호하세요?)\n\n👨: I prefer remote work because it saves commuting time.\n(저는 출퇴근 시간을 아껴주는 재택근무를 선호합니다.)\n\n👩: But don't you feel isolated sometimes?\n(하지만 가끔 고립감을 느끼진 않나요?)\n\n👨: That is a downside. I miss chatting with colleagues.\n(그게 단점이죠. 동료들과 수다 떨던 게 그리워요.)\n\n👩: I think a hybrid model is the best solution.\n(저는 하이브리드 모델이 최선책이라고 생각해요.)\n\n👨: Combining both offers flexibility and social interaction.\n(두 가지를 결합하면 유연성과 사회적 교류를 모두 얻죠.)\n\n👩: Is it easy to separate work and life at home?\n(집에서 일과 생활을 분리하는 게 쉬운가요?)\n\n👨: Not really. I sometimes work late into the night.\n(별로요. 가끔 밤늦게까지 일하게 되더라고요.)\n\n👩: Setting boundaries is crucial for mental health.\n(경계를 설정하는 게 정신 건강에 중요해요.)\n\n👨: I agree. I need to set a strict schedule.\n(동의해요. 엄격한 스케줄을 짜야겠어요.)"""),
        ("고급 (Advanced)", "04. 소셜 미디어", """👩: How much time do you spend on social media?\n(소셜 미디어에 시간을 얼마나 쓰세요?)\n\n👨: Too much, honestly. It's very distracting.\n(솔직히 너무 많이요. 주의가 꽤 산만해져요.)\n\n👩: Social media can distort our view of reality.\n(소셜 미디어는 현실에 대한 우리의 시각을 왜곡할 수 있죠.)\n\n👨: People only post their best moments online.\n(사람들은 온라인에 자신의 최고의 순간만 올리니까요.)\n\n👩: That makes others feel inadequate or jealous.\n(그게 다른 사람들을 부족하거나 질투 나게 만들죠.)\n\n👨: However, it is also a powerful tool for connection.\n(하지만 연결을 위한 강력한 도구이기도 합니다.)\n\n👩: True. I keep in touch with old friends through it.\n(맞아요. 전 그걸로 옛 친구들과 연락해요.)\n\n👨: We just need to use it wisely and moderately.\n(우리는 그저 현명하고 적당하게 사용할 필요가 있어요.)\n\n👩: I am trying to do a digital detox these days.\n(저는 요즘 디지털 디톡스를 하려고 노력 중이에요.)\n\n👨: That is a healthy habit to develop.\n(기르기에 아주 건강한 습관이네요.)"""),
        ("고급 (Advanced)", "05. 경제/투자", """👩: Are you interested in the stock market?\n(주식 시장에 관심 있으세요?)\n\n👨: Yes, I invest a small portion of my savings.\n(네, 저축한 돈의 일부를 투자하고 있어요.)\n\n👩: The market is very volatile these days.\n(요즘 시장 변동성이 매우 크더라고요.)\n\n👨: High risk brings high return, as they say.\n(하이 리스크 하이 리턴이라는 말이 있잖아요.)\n\n👩: Do you focus on short-term or long-term investment?\n(단기 투자와 장기 투자 중 어디에 집중하세요?)\n\n👨: I believe in long-term value investment.\n(저는 장기 가치 투자를 믿습니다.)\n\n👩: Inflation is affecting everyone's purchasing power.\n(인플레이션이 모두의 구매력에 영향을 미치고 있어요.)\n\n👨: That's why keeping cash is not always safe.\n(그래서 현금을 쥐고 있는 게 항상 안전한 건 아니죠.)\n\n👩: Financial literacy is important for everyone.\n(금융 지식은 모든 사람에게 중요해요.)\n\n👨: I totally agree. Schools should teach it.\n(전적으로 동의합니다. 학교에서 가르쳐야 해요.)"""),
        ("고급 (Advanced)", "06. 문화 차이", """👩: Have you experienced culture shock while traveling?\n(여행 중에 문화 충격을 겪은 적 있나요?)\n\n👨: In Europe, I was surprised that water wasn't free.\n(유럽에서 물이 공짜가 아니라서 놀랐어요.)\n\n👩: Also, tipping culture varies from country to country.\n(그리고 팁 문화도 나라마다 다르죠.)\n\n👨: In Korea, we don't tip, so it was confusing.\n(한국에선 팁을 안 주니까 헷갈리더라고요.)\n\n👩: Understanding local customs shows respect.\n(현지 관습을 이해하는 건 존중을 보여주는 거죠.)\n\n👨: I learned that eye contact is important in the West.\n(서양에서는 눈 맞춤이 중요하다는 걸 배웠어요.)\n\n👩: In some Asian cultures, it can be seen as rude.\n(일부 아시아 문화권에선 그게 무례해 보일 수 있고요.)\n\n👨: Diversity makes the world more interesting.\n(다양성이 세상을 더 흥미롭게 만들죠.)\n\n👩: We should be open-minded to different perspectives.\n(우리는 다른 관점에 대해 마음을 열어야 해요.)\n\n👨: Travel is the best way to learn that.\n(여행이 그걸 배우는 최고의 방법이죠.)"""),
        ("고급 (Advanced)", "07. 교육 제도", """👩: What do you think about the Korean education system?\n(한국의 교육 제도에 대해 어떻게 생각하세요?)\n\n👨: It is very competitive and stressful for students.\n(학생들에게 매우 경쟁적이고 스트레스가 많죠.)\n\n👩: But it produces high academic standards.\n(하지만 높은 학업 수준을 만들어내긴 하잖아요.)\n\n👨: True, but creativity is often overlooked.\n(맞아요, 하지만 창의성은 종종 간과되곤 하죠.)\n\n👩: We focus too much on memorization and tests.\n(우리는 암기와 시험에 너무 집중해요.)\n\n👨: Education should encourage critical thinking.\n(교육은 비판적 사고를 장려해야 합니다.)\n\n👩: Lifelong learning is becoming more important.\n(평생교육이 점점 더 중요해지고 있어요.)\n\n👨: The world changes fast, so we must keep learning.\n(세상이 빨리 변하니 우리는 계속 배워야 해요.)\n\n👩: Online education has made learning accessible.\n(온라인 교육이 배움을 접근하기 쉽게 만들었어요.)\n\n👨: It is a positive change for the future.\n(그건 미래를 위한 긍정적인 변화죠.)"""),
        ("고급 (Advanced)", "08. 우주 탐사", """👩: Do you think humans will live on Mars someday?\n(언젠가 인간이 화성에 살 거라고 생각하세요?)\n\n👨: It is possible, but it will take a long time.\n(가능은 하겠지만, 시간이 오래 걸리겠죠.)\n\n👩: Space exploration requires huge budgets.\n(우주 탐사에는 막대한 예산이 필요해요.)\n\n👨: Some people argue we should fix Earth first.\n(어떤 사람들은 지구부터 고쳐야 한다고 주장하죠.)\n\n👩: But space technology also benefits life on Earth.\n(하지만 우주 기술은 지구의 삶에도 혜택을 줘요.)\n\n👨: Like GPS and satellite communication?\n(GPS나 위성 통신 같은 거요?)\n\n👨: Exactly. Innovation comes from exploring the unknown.\n(바로 그거죠. 혁신은 미지를 탐험하는 데서 오니까요.)\n\n👩: Would you travel to space if you had the chance?\n(기회가 된다면 우주 여행을 가시겠어요?)\n\n👨: It sounds scary but exciting. Maybe yes.\n(무섭지만 흥미롭네요. 아마도 갈 것 같아요.)\n\n👩: The universe is vast and full of mysteries.\n(우주는 광활하고 미스터리로 가득 차 있죠.)"""),
        ("고급 (Advanced)", "09. 일과 삶의 균형", """👩: Is work-life balance important to you?\n(일과 삶의 균형(워라밸)이 당신에게 중요한가요?)\n\n👨: Yes, I prioritize spending time with my family.\n(네, 저는 가족과 시간을 보내는 걸 최우선으로 해요.)\n\n👩: Many people suffer from burnout these days.\n(요즘 많은 사람들이 번아웃으로 고생하죠.)\n\n👨: Overworking reduces efficiency in the long run.\n(과로는 장기적으로 효율성을 떨어뜨립니다.)\n\n👩: Companies are starting to offer more vacation days.\n(기업들이 더 많은 휴가를 제공하기 시작했어요.)\n\n👨: Rest is essential for creativity and energy.\n(휴식은 창의력과 에너지를 위해 필수적이죠.)\n\n👩: What do you do to recharge yourself?\n(재충전을 위해 무엇을 하시나요?)\n\n👨: I usually go camping or read books.\n(저는 보통 캠핑을 가거나 책을 읽어요.)\n\n👩: Disconnecting from work is a skill we need.\n(일에서 로그아웃하는 것도 우리에게 필요한 기술이에요.)\n\n👨: Happiness comes from a balanced life.\n(행복은 균형 잡힌 삶에서 오니까요.)"""),
        ("고급 (Advanced)", "10. 리더십", """👩: What makes a good leader?\n(무엇이 좋은 리더를 만든다고 생각하세요?)\n\n👨: A good leader listens to their team members.\n(좋은 리더는 팀원들의 말을 경청합니다.)\n\n👩: Also, taking responsibility is crucial.\n(또한, 책임을 지는 것도 매우 중요하죠.)\n\n👨: Leaders should inspire others, not just give orders.\n(리더는 명령만 하는 게 아니라 영감을 줘야 해요.)\n\n👩: Do you think leaders are born or made?\n(리더는 타고나는 걸까요, 만들어지는 걸까요?)\n\n👨: I think leadership skills can be learned.\n(저는 리더십 기술은 배울 수 있다고 생각해요.)\n\n👩: Communication is the key to effective leadership.\n(소통이 효과적인 리더십의 핵심이죠.)\n\n👨: Trust is also the foundation of any team.\n(신뢰 또한 모든 팀의 기반입니다.)\n\n👩: It is hard to satisfy everyone.\n(모두를 만족시키는 건 어렵죠.)\n\n👨: True, decision-making is a lonely task.\n(맞아요, 의사결정은 외로운 작업이죠.)""")
    ]

    # 데이터 삽입
    cursor.executemany("INSERT INTO study_data (level, topic, sentences) VALUES (?, ?, ?)", study_list)
    conn.commit()
    conn.close()

def get_topics_by_level(level):
    """해당 레벨의 주제 리스트를 반환하는 함수"""
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    cursor.execute("SELECT topic FROM study_data WHERE level=?", (level,))
    topics = sorted(list(set([row[0] for row in cursor.fetchall()])))
    conn.close()
    return topics

def get_content_by_topic(level, topic):
    """특정 주제의 대화 내용을 반환하는 함수"""
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    cursor.execute("SELECT sentences FROM study_data WHERE level=? AND topic=?", (level, topic))
    result = cursor.fetchone()
    conn.close()
    return result[0] if result else None